apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: shopping
  name: manage-pods
subjects:
  - kind: User
    name: 'Bob Smith'
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: manage-pods
  apiGroup: rbac.authorization.k8s.io
