apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shopping
  name: manage-pods
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
